version: 2
jobs:
  build:
    working_directory: ~/jio-lib

    docker:
      - image: circleci/openjdk:8-jdk-browsers

    steps:

      - checkout

      - run: mvn

      - store_test_results:
          path: target/surefire-reports

      - store_artifacts:
          path: target/JioLib-1.2.0-SNAPSHOT-jar-with-dependencies.jar

      - store_artifacts:
          path: target/JioLib-1.2.0-SNAPSHOT.jar

      - store_artifacts:
          path: target/JioLib-1.2.0-SNAPSHOT-site.jar
